sonar.projectKey=com.xuena:supplier-performance-frontend
sonar.projectName=供应商绩效分析系统-前端
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.css,**/vite.svg
sonar.sourceEncoding=UTF-8

sonar.eslint.reportPaths=eslint-report.json
