sonar.projectKey=com.xuena:supplier-performance
sonar.projectName=供应商绩效分析系统
sonar.projectVersion=1.0.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.sourceEncoding=UTF-8

sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=src/main/resources/**,**/GeneratePassword.java
sonar.coverage.exclusions=**/entity/**,**/config/**,**/enums/**,**/vo/**,**/filter/**,**/SupplierApplication.java,**/GeneratePassword.java

sonar.cpd.exclusions=**/entity/**,**/vo/**,**/enums/**

sonar.java.source=17
