ALTER TABLE sp_supplier_pool 
ADD COLUMN create_name VARCHAR(100) NULL COMMENT '创建人',
ADD COLUMN create_id VARCHAR(64) NULL COMMENT '创建人ID',
ADD COLUMN create_date DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
ADD COLUMN update_name VARCHAR(100) NULL COMMENT '更新人',
ADD COLUMN update_id VARCHAR(64) NULL COMMENT '更新人ID',
ADD COLUMN update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE sp_category 
ADD COLUMN create_name VARCHAR(100) NULL COMMENT '创建人',
ADD COLUMN create_id VARCHAR(64) NULL COMMENT '创建人ID',
ADD COLUMN create_date DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
ADD COLUMN update_name VARCHAR(100) NULL COMMENT '更新人',
ADD COLUMN update_id VARCHAR(64) NULL COMMENT '更新人ID',
ADD COLUMN update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE sp_monthly_assessment 
ADD COLUMN create_name VARCHAR(100) NULL COMMENT '创建人',
ADD COLUMN create_id VARCHAR(64) NULL COMMENT '创建人ID',
ADD COLUMN create_date DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
ADD COLUMN update_name VARCHAR(100) NULL COMMENT '更新人',
ADD COLUMN update_id VARCHAR(64) NULL COMMENT '更新人ID',
ADD COLUMN update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE sp_department_score 
ADD COLUMN create_name VARCHAR(100) NULL COMMENT '创建人',
ADD COLUMN create_id VARCHAR(64) NULL COMMENT '创建人ID',
ADD COLUMN create_date DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
ADD COLUMN update_name VARCHAR(100) NULL COMMENT '更新人',
ADD COLUMN update_id VARCHAR(64) NULL COMMENT '更新人ID',
ADD COLUMN update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE sp_meeting_note 
ADD COLUMN create_name VARCHAR(100) NULL COMMENT '创建人',
ADD COLUMN create_id VARCHAR(64) NULL COMMENT '创建人ID',
ADD COLUMN create_date DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
ADD COLUMN update_name VARCHAR(100) NULL COMMENT '更新人',
ADD COLUMN update_id VARCHAR(64) NULL COMMENT '更新人ID',
ADD COLUMN update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE sp_user 
ADD COLUMN create_name VARCHAR(100) NULL COMMENT '创建人',
ADD COLUMN create_id VARCHAR(64) NULL COMMENT '创建人ID',
ADD COLUMN create_date DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
ADD COLUMN update_name VARCHAR(100) NULL COMMENT '更新人',
ADD COLUMN update_id VARCHAR(64) NULL COMMENT '更新人ID',
ADD COLUMN update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE sp_role 
ADD COLUMN create_name VARCHAR(100) NULL COMMENT '创建人',
ADD COLUMN create_id VARCHAR(64) NULL COMMENT '创建人ID',
ADD COLUMN create_date DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
ADD COLUMN update_name VARCHAR(100) NULL COMMENT '更新人',
ADD COLUMN update_id VARCHAR(64) NULL COMMENT '更新人ID',
ADD COLUMN update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE sp_permission 
ADD COLUMN create_name VARCHAR(100) NULL COMMENT '创建人',
ADD COLUMN create_id VARCHAR(64) NULL COMMENT '创建人ID',
ADD COLUMN create_date DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
ADD COLUMN update_name VARCHAR(100) NULL COMMENT '更新人',
ADD COLUMN update_id VARCHAR(64) NULL COMMENT '更新人ID',
ADD COLUMN update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE sp_menu 
ADD COLUMN create_name VARCHAR(100) NULL COMMENT '创建人',
ADD COLUMN create_id VARCHAR(64) NULL COMMENT '创建人ID',
ADD COLUMN create_date DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
ADD COLUMN update_name VARCHAR(100) NULL COMMENT '更新人',
ADD COLUMN update_id VARCHAR(64) NULL COMMENT '更新人ID',
ADD COLUMN update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE sp_user_role 
ADD COLUMN create_name VARCHAR(100) NULL COMMENT '创建人',
ADD COLUMN create_id VARCHAR(64) NULL COMMENT '创建人ID',
ADD COLUMN create_date DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
ADD COLUMN update_name VARCHAR(100) NULL COMMENT '更新人',
ADD COLUMN update_id VARCHAR(64) NULL COMMENT '更新人ID',
ADD COLUMN update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE sp_role_permission 
ADD COLUMN create_name VARCHAR(100) NULL COMMENT '创建人',
ADD COLUMN create_id VARCHAR(64) NULL COMMENT '创建人ID',
ADD COLUMN create_date DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
ADD COLUMN update_name VARCHAR(100) NULL COMMENT '更新人',
ADD COLUMN update_id VARCHAR(64) NULL COMMENT '更新人ID',
ADD COLUMN update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE sp_role_menu 
ADD COLUMN create_name VARCHAR(100) NULL COMMENT '创建人',
ADD COLUMN create_id VARCHAR(64) NULL COMMENT '创建人ID',
ADD COLUMN create_date DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
ADD COLUMN update_name VARCHAR(100) NULL COMMENT '更新人',
ADD COLUMN update_id VARCHAR(64) NULL COMMENT '更新人ID',
ADD COLUMN update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE sp_file 
ADD COLUMN create_name VARCHAR(100) NULL COMMENT '创建人',
ADD COLUMN create_id VARCHAR(64) NULL COMMENT '创建人ID',
ADD COLUMN create_date DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
ADD COLUMN update_name VARCHAR(100) NULL COMMENT '更新人',
ADD COLUMN update_id VARCHAR(64) NULL COMMENT '更新人ID',
ADD COLUMN update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE sp_dict 
ADD COLUMN create_name VARCHAR(100) NULL COMMENT '创建人',
ADD COLUMN create_id VARCHAR(64) NULL COMMENT '创建人ID',
ADD COLUMN create_date DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
ADD COLUMN update_name VARCHAR(100) NULL COMMENT '更新人',
ADD COLUMN update_id VARCHAR(64) NULL COMMENT '更新人ID',
ADD COLUMN update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
